### ISSUE TITLE
Critical: Ingen tagg för labb 1

### ISSUE THREAD

**Issue by WilliamFrisk** [Sebbe213/TDA553-lab1#1]
## CRITICAL ##
Ni behöver tagga den committen som är er inlämning för labb 1. Här finns en guide: https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/managing-tags

**Comment by Sebbe213** [comment]
Hej! Nu har jag skapat en tag på den sista committen vi gjorde innan inlämning. Hoppas att det blev rätt.
